// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tmpl_DE84D583.proto

package pb_templates

import (
	proto "github.com/golang/protobuf/proto"
	pb_oip "github.com/oipwg/proto/go/pb_oip"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// SimpleCoinSale
// de84d583503894e2e865a0020e8873ec20064461c6de03136b973e42d1dcdb64
type Tmpl_DE84D583 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin        *pb_oip.Txid `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Destination string       `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount      uint32       `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Scale       uint32       `protobuf:"varint,4,opt,name=scale,proto3" json:"scale,omitempty"`
	Duration    uint32       `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Indefinite  bool         `protobuf:"varint,6,opt,name=indefinite,proto3" json:"indefinite,omitempty"`
}

func (x *Tmpl_DE84D583) Reset() {
	*x = Tmpl_DE84D583{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmpl_DE84D583_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmpl_DE84D583) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmpl_DE84D583) ProtoMessage() {}

func (x *Tmpl_DE84D583) ProtoReflect() protoreflect.Message {
	mi := &file_tmpl_DE84D583_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmpl_DE84D583.ProtoReflect.Descriptor instead.
func (*Tmpl_DE84D583) Descriptor() ([]byte, []int) {
	return file_tmpl_DE84D583_proto_rawDescGZIP(), []int{0}
}

func (x *Tmpl_DE84D583) GetCoin() *pb_oip.Txid {
	if x != nil {
		return x.Coin
	}
	return nil
}

func (x *Tmpl_DE84D583) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Tmpl_DE84D583) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Tmpl_DE84D583) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Tmpl_DE84D583) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Tmpl_DE84D583) GetIndefinite() bool {
	if x != nil {
		return x.Indefinite
	}
	return false
}

var File_tmpl_DE84D583_proto protoreflect.FileDescriptor

var file_tmpl_DE84D583_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x44, 0x45, 0x38, 0x34, 0x44, 0x35, 0x38, 0x33, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x0a, 0x74, 0x78, 0x69, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x44,
	0x45, 0x38, 0x34, 0x44, 0x35, 0x38, 0x33, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x78, 0x69, 0x64, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x6e, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x2f, 0x70, 0x62, 0x5f,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x3b, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmpl_DE84D583_proto_rawDescOnce sync.Once
	file_tmpl_DE84D583_proto_rawDescData = file_tmpl_DE84D583_proto_rawDesc
)

func file_tmpl_DE84D583_proto_rawDescGZIP() []byte {
	file_tmpl_DE84D583_proto_rawDescOnce.Do(func() {
		file_tmpl_DE84D583_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmpl_DE84D583_proto_rawDescData)
	})
	return file_tmpl_DE84D583_proto_rawDescData
}

var file_tmpl_DE84D583_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tmpl_DE84D583_proto_goTypes = []interface{}{
	(*Tmpl_DE84D583)(nil), // 0: oipProto.templates.tmpl_DE84D583
	(*pb_oip.Txid)(nil),   // 1: oipProto.Txid
}
var file_tmpl_DE84D583_proto_depIdxs = []int32{
	1, // 0: oipProto.templates.tmpl_DE84D583.coin:type_name -> oipProto.Txid
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tmpl_DE84D583_proto_init() }
func file_tmpl_DE84D583_proto_init() {
	if File_tmpl_DE84D583_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmpl_DE84D583_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmpl_DE84D583); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmpl_DE84D583_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmpl_DE84D583_proto_goTypes,
		DependencyIndexes: file_tmpl_DE84D583_proto_depIdxs,
		MessageInfos:      file_tmpl_DE84D583_proto_msgTypes,
	}.Build()
	File_tmpl_DE84D583_proto = out.File
	file_tmpl_DE84D583_proto_rawDesc = nil
	file_tmpl_DE84D583_proto_goTypes = nil
	file_tmpl_DE84D583_proto_depIdxs = nil
}
