// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tmpl_2670B072.proto

package pb_templates

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/oipwg/proto/go/pb_oip"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Song
// 2670b072c07eda38a423bd1dbadc629df200d644ff98fc2768aaa00203c1efda
type Tmpl_2670B072 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Genre    string `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	Duration uint32 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Artist   string `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *Tmpl_2670B072) Reset() {
	*x = Tmpl_2670B072{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmpl_2670B072_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmpl_2670B072) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmpl_2670B072) ProtoMessage() {}

func (x *Tmpl_2670B072) ProtoReflect() protoreflect.Message {
	mi := &file_tmpl_2670B072_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmpl_2670B072.ProtoReflect.Descriptor instead.
func (*Tmpl_2670B072) Descriptor() ([]byte, []int) {
	return file_tmpl_2670B072_proto_rawDescGZIP(), []int{0}
}

func (x *Tmpl_2670B072) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tmpl_2670B072) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Tmpl_2670B072) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Tmpl_2670B072) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

var File_tmpl_2670B072_proto protoreflect.FileDescriptor

var file_tmpl_2670B072_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x32, 0x36, 0x37, 0x30, 0x42, 0x30, 0x37, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x0a, 0x74, 0x78, 0x69, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x0d, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x32, 0x36,
	0x37, 0x30, 0x42, 0x30, 0x37, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x2f, 0x70, 0x62, 0x5f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x3b, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmpl_2670B072_proto_rawDescOnce sync.Once
	file_tmpl_2670B072_proto_rawDescData = file_tmpl_2670B072_proto_rawDesc
)

func file_tmpl_2670B072_proto_rawDescGZIP() []byte {
	file_tmpl_2670B072_proto_rawDescOnce.Do(func() {
		file_tmpl_2670B072_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmpl_2670B072_proto_rawDescData)
	})
	return file_tmpl_2670B072_proto_rawDescData
}

var file_tmpl_2670B072_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tmpl_2670B072_proto_goTypes = []interface{}{
	(*Tmpl_2670B072)(nil), // 0: oipProto.templates.tmpl_2670B072
}
var file_tmpl_2670B072_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tmpl_2670B072_proto_init() }
func file_tmpl_2670B072_proto_init() {
	if File_tmpl_2670B072_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmpl_2670B072_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmpl_2670B072); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmpl_2670B072_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmpl_2670B072_proto_goTypes,
		DependencyIndexes: file_tmpl_2670B072_proto_depIdxs,
		MessageInfos:      file_tmpl_2670B072_proto_msgTypes,
	}.Build()
	File_tmpl_2670B072_proto = out.File
	file_tmpl_2670B072_proto_rawDesc = nil
	file_tmpl_2670B072_proto_goTypes = nil
	file_tmpl_2670B072_proto_depIdxs = nil
}
