// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tmpl_D8D0F22C.proto

package pb_templates

import (
	proto "github.com/golang/protobuf/proto"
	pb_oip "github.com/oipwg/proto/go/pb_oip"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Tmpl_D8D0F22C_Network int32

const (
	Tmpl_D8D0F22C_NETWORK_UNDEFINED  Tmpl_D8D0F22C_Network = 0
	Tmpl_D8D0F22C_NETWORK_IPFS       Tmpl_D8D0F22C_Network = 1
	Tmpl_D8D0F22C_NETWORK_BITTORRENT Tmpl_D8D0F22C_Network = 2
	Tmpl_D8D0F22C_NETWORK_SIA        Tmpl_D8D0F22C_Network = 3
	Tmpl_D8D0F22C_NETWORK_STORJ      Tmpl_D8D0F22C_Network = 4
)

// Enum value maps for Tmpl_D8D0F22C_Network.
var (
	Tmpl_D8D0F22C_Network_name = map[int32]string{
		0: "NETWORK_UNDEFINED",
		1: "NETWORK_IPFS",
		2: "NETWORK_BITTORRENT",
		3: "NETWORK_SIA",
		4: "NETWORK_STORJ",
	}
	Tmpl_D8D0F22C_Network_value = map[string]int32{
		"NETWORK_UNDEFINED":  0,
		"NETWORK_IPFS":       1,
		"NETWORK_BITTORRENT": 2,
		"NETWORK_SIA":        3,
		"NETWORK_STORJ":      4,
	}
)

func (x Tmpl_D8D0F22C_Network) Enum() *Tmpl_D8D0F22C_Network {
	p := new(Tmpl_D8D0F22C_Network)
	*p = x
	return p
}

func (x Tmpl_D8D0F22C_Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tmpl_D8D0F22C_Network) Descriptor() protoreflect.EnumDescriptor {
	return file_tmpl_D8D0F22C_proto_enumTypes[0].Descriptor()
}

func (Tmpl_D8D0F22C_Network) Type() protoreflect.EnumType {
	return &file_tmpl_D8D0F22C_proto_enumTypes[0]
}

func (x Tmpl_D8D0F22C_Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tmpl_D8D0F22C_Network.Descriptor instead.
func (Tmpl_D8D0F22C_Network) EnumDescriptor() ([]byte, []int) {
	return file_tmpl_D8D0F22C_proto_rawDescGZIP(), []int{0, 0}
}

// CommercialContent
// d8d0f22c79f3d5670874a4f0e439b7cdc130dd213759e56eb8d2f3081e0e7dda
type Tmpl_D8D0F22C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location      string                `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Network       Tmpl_D8D0F22C_Network `protobuf:"varint,2,opt,name=network,proto3,enum=oipProto.templates.Tmpl_D8D0F22C_Network" json:"network,omitempty"`
	Terms         []*pb_oip.Txid        `protobuf:"bytes,3,rep,name=terms,proto3" json:"terms,omitempty"`
	EmbeddedTerms []uint32              `protobuf:"fixed32,4,rep,packed,name=embedded_terms,json=embeddedTerms,proto3" json:"embedded_terms,omitempty"`
}

func (x *Tmpl_D8D0F22C) Reset() {
	*x = Tmpl_D8D0F22C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmpl_D8D0F22C_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmpl_D8D0F22C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmpl_D8D0F22C) ProtoMessage() {}

func (x *Tmpl_D8D0F22C) ProtoReflect() protoreflect.Message {
	mi := &file_tmpl_D8D0F22C_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmpl_D8D0F22C.ProtoReflect.Descriptor instead.
func (*Tmpl_D8D0F22C) Descriptor() ([]byte, []int) {
	return file_tmpl_D8D0F22C_proto_rawDescGZIP(), []int{0}
}

func (x *Tmpl_D8D0F22C) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Tmpl_D8D0F22C) GetNetwork() Tmpl_D8D0F22C_Network {
	if x != nil {
		return x.Network
	}
	return Tmpl_D8D0F22C_NETWORK_UNDEFINED
}

func (x *Tmpl_D8D0F22C) GetTerms() []*pb_oip.Txid {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *Tmpl_D8D0F22C) GetEmbeddedTerms() []uint32 {
	if x != nil {
		return x.EmbeddedTerms
	}
	return nil
}

var File_tmpl_D8D0F22C_proto protoreflect.FileDescriptor

var file_tmpl_D8D0F22C_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x44, 0x38, 0x44, 0x30, 0x46, 0x32, 0x32, 0x43, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x0a, 0x74, 0x78, 0x69, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x02, 0x0a, 0x0d, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x44,
	0x38, 0x44, 0x30, 0x46, 0x32, 0x32, 0x43, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x44,
	0x38, 0x44, 0x30, 0x46, 0x32, 0x32, 0x43, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x24, 0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x78, 0x69, 0x64, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x07, 0x52, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64,
	0x54, 0x65, 0x72, 0x6d, 0x73, 0x22, 0x6e, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x12, 0x15, 0x0a, 0x11, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x55, 0x4e, 0x44, 0x45,
	0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57, 0x4f,
	0x52, 0x4b, 0x5f, 0x49, 0x50, 0x46, 0x53, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4e, 0x45, 0x54,
	0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x42, 0x49, 0x54, 0x54, 0x4f, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x10,
	0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x49, 0x41,
	0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54,
	0x4f, 0x52, 0x4a, 0x10, 0x04, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x2f, 0x70, 0x62, 0x5f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x3b, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmpl_D8D0F22C_proto_rawDescOnce sync.Once
	file_tmpl_D8D0F22C_proto_rawDescData = file_tmpl_D8D0F22C_proto_rawDesc
)

func file_tmpl_D8D0F22C_proto_rawDescGZIP() []byte {
	file_tmpl_D8D0F22C_proto_rawDescOnce.Do(func() {
		file_tmpl_D8D0F22C_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmpl_D8D0F22C_proto_rawDescData)
	})
	return file_tmpl_D8D0F22C_proto_rawDescData
}

var file_tmpl_D8D0F22C_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tmpl_D8D0F22C_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tmpl_D8D0F22C_proto_goTypes = []interface{}{
	(Tmpl_D8D0F22C_Network)(0), // 0: oipProto.templates.tmpl_D8D0F22C.Network
	(*Tmpl_D8D0F22C)(nil),      // 1: oipProto.templates.tmpl_D8D0F22C
	(*pb_oip.Txid)(nil),        // 2: oipProto.Txid
}
var file_tmpl_D8D0F22C_proto_depIdxs = []int32{
	0, // 0: oipProto.templates.tmpl_D8D0F22C.network:type_name -> oipProto.templates.tmpl_D8D0F22C.Network
	2, // 1: oipProto.templates.tmpl_D8D0F22C.terms:type_name -> oipProto.Txid
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tmpl_D8D0F22C_proto_init() }
func file_tmpl_D8D0F22C_proto_init() {
	if File_tmpl_D8D0F22C_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmpl_D8D0F22C_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmpl_D8D0F22C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmpl_D8D0F22C_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmpl_D8D0F22C_proto_goTypes,
		DependencyIndexes: file_tmpl_D8D0F22C_proto_depIdxs,
		EnumInfos:         file_tmpl_D8D0F22C_proto_enumTypes,
		MessageInfos:      file_tmpl_D8D0F22C_proto_msgTypes,
	}.Build()
	File_tmpl_D8D0F22C_proto = out.File
	file_tmpl_D8D0F22C_proto_rawDesc = nil
	file_tmpl_D8D0F22C_proto_goTypes = nil
	file_tmpl_D8D0F22C_proto_depIdxs = nil
}
