// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tmpl_433C2783.proto

package pb_templates

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Registered Publisher
type Tmpl_433C2783 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FloBip44XPub string `protobuf:"bytes,2,opt,name=floBip44XPub,proto3" json:"floBip44XPub,omitempty"`
}

func (x *Tmpl_433C2783) Reset() {
	*x = Tmpl_433C2783{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmpl_433C2783_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmpl_433C2783) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmpl_433C2783) ProtoMessage() {}

func (x *Tmpl_433C2783) ProtoReflect() protoreflect.Message {
	mi := &file_tmpl_433C2783_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmpl_433C2783.ProtoReflect.Descriptor instead.
func (*Tmpl_433C2783) Descriptor() ([]byte, []int) {
	return file_tmpl_433C2783_proto_rawDescGZIP(), []int{0}
}

func (x *Tmpl_433C2783) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tmpl_433C2783) GetFloBip44XPub() string {
	if x != nil {
		return x.FloBip44XPub
	}
	return ""
}

var File_tmpl_433C2783_proto protoreflect.FileDescriptor

var file_tmpl_433C2783_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x34, 0x33, 0x33, 0x43, 0x32, 0x37, 0x38, 0x33, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x0d, 0x74, 0x6d, 0x70,
	0x6c, 0x5f, 0x34, 0x33, 0x33, 0x43, 0x32, 0x37, 0x38, 0x33, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x42, 0x69, 0x70, 0x34, 0x34, 0x58, 0x50, 0x75, 0x62, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x42, 0x69, 0x70, 0x34, 0x34, 0x58, 0x50,
	0x75, 0x62, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x2f, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x3b, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmpl_433C2783_proto_rawDescOnce sync.Once
	file_tmpl_433C2783_proto_rawDescData = file_tmpl_433C2783_proto_rawDesc
)

func file_tmpl_433C2783_proto_rawDescGZIP() []byte {
	file_tmpl_433C2783_proto_rawDescOnce.Do(func() {
		file_tmpl_433C2783_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmpl_433C2783_proto_rawDescData)
	})
	return file_tmpl_433C2783_proto_rawDescData
}

var file_tmpl_433C2783_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tmpl_433C2783_proto_goTypes = []interface{}{
	(*Tmpl_433C2783)(nil), // 0: oipProto.templates.tmpl_433C2783
}
var file_tmpl_433C2783_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tmpl_433C2783_proto_init() }
func file_tmpl_433C2783_proto_init() {
	if File_tmpl_433C2783_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmpl_433C2783_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmpl_433C2783); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmpl_433C2783_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmpl_433C2783_proto_goTypes,
		DependencyIndexes: file_tmpl_433C2783_proto_depIdxs,
		MessageInfos:      file_tmpl_433C2783_proto_msgTypes,
	}.Build()
	File_tmpl_433C2783_proto = out.File
	file_tmpl_433C2783_proto_rawDesc = nil
	file_tmpl_433C2783_proto_goTypes = nil
	file_tmpl_433C2783_proto_depIdxs = nil
}
