// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tmpl_6E6D471D.proto

package pb_templates

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Tmpl_6E6D471D_Options int32

const (
	Tmpl_6E6D471D_OPTIONS_UNDEFINED Tmpl_6E6D471D_Options = 0
	Tmpl_6E6D471D_OPTIONS_ONE       Tmpl_6E6D471D_Options = 1
	Tmpl_6E6D471D_OPTIONS_TWO       Tmpl_6E6D471D_Options = 2
	Tmpl_6E6D471D_OPTIONS_THREE     Tmpl_6E6D471D_Options = 3
)

// Enum value maps for Tmpl_6E6D471D_Options.
var (
	Tmpl_6E6D471D_Options_name = map[int32]string{
		0: "OPTIONS_UNDEFINED",
		1: "OPTIONS_ONE",
		2: "OPTIONS_TWO",
		3: "OPTIONS_THREE",
	}
	Tmpl_6E6D471D_Options_value = map[string]int32{
		"OPTIONS_UNDEFINED": 0,
		"OPTIONS_ONE":       1,
		"OPTIONS_TWO":       2,
		"OPTIONS_THREE":     3,
	}
)

func (x Tmpl_6E6D471D_Options) Enum() *Tmpl_6E6D471D_Options {
	p := new(Tmpl_6E6D471D_Options)
	*p = x
	return p
}

func (x Tmpl_6E6D471D_Options) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tmpl_6E6D471D_Options) Descriptor() protoreflect.EnumDescriptor {
	return file_tmpl_6E6D471D_proto_enumTypes[0].Descriptor()
}

func (Tmpl_6E6D471D_Options) Type() protoreflect.EnumType {
	return &file_tmpl_6E6D471D_proto_enumTypes[0]
}

func (x Tmpl_6E6D471D_Options) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tmpl_6E6D471D_Options.Descriptor instead.
func (Tmpl_6E6D471D_Options) EnumDescriptor() ([]byte, []int) {
	return file_tmpl_6E6D471D_proto_rawDescGZIP(), []int{0, 0}
}

type Tmpl_6E6D471D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string                `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Enum Tmpl_6E6D471D_Options `protobuf:"varint,2,opt,name=enum,proto3,enum=oipProto.templates.Tmpl_6E6D471D_Options" json:"enum,omitempty"`
}

func (x *Tmpl_6E6D471D) Reset() {
	*x = Tmpl_6E6D471D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmpl_6E6D471D_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmpl_6E6D471D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmpl_6E6D471D) ProtoMessage() {}

func (x *Tmpl_6E6D471D) ProtoReflect() protoreflect.Message {
	mi := &file_tmpl_6E6D471D_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmpl_6E6D471D.ProtoReflect.Descriptor instead.
func (*Tmpl_6E6D471D) Descriptor() ([]byte, []int) {
	return file_tmpl_6E6D471D_proto_rawDescGZIP(), []int{0}
}

func (x *Tmpl_6E6D471D) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Tmpl_6E6D471D) GetEnum() Tmpl_6E6D471D_Options {
	if x != nil {
		return x.Enum
	}
	return Tmpl_6E6D471D_OPTIONS_UNDEFINED
}

var File_tmpl_6E6D471D_proto protoreflect.FileDescriptor

var file_tmpl_6E6D471D_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x36, 0x45, 0x36, 0x44, 0x34, 0x37, 0x31, 0x44, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x0d, 0x74, 0x6d,
	0x70, 0x6c, 0x5f, 0x36, 0x45, 0x36, 0x44, 0x34, 0x37, 0x31, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x3d, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e,
	0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x2e, 0x74, 0x6d, 0x70, 0x6c, 0x5f, 0x36, 0x45, 0x36, 0x44, 0x34, 0x37, 0x31, 0x44,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x55,
	0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x50, 0x54,
	0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x4f, 0x4e, 0x45, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x54, 0x57, 0x4f,
	0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x54, 0x48,
	0x52, 0x45, 0x45, 0x10, 0x03, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x2f, 0x70, 0x62, 0x5f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x3b, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmpl_6E6D471D_proto_rawDescOnce sync.Once
	file_tmpl_6E6D471D_proto_rawDescData = file_tmpl_6E6D471D_proto_rawDesc
)

func file_tmpl_6E6D471D_proto_rawDescGZIP() []byte {
	file_tmpl_6E6D471D_proto_rawDescOnce.Do(func() {
		file_tmpl_6E6D471D_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmpl_6E6D471D_proto_rawDescData)
	})
	return file_tmpl_6E6D471D_proto_rawDescData
}

var file_tmpl_6E6D471D_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tmpl_6E6D471D_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tmpl_6E6D471D_proto_goTypes = []interface{}{
	(Tmpl_6E6D471D_Options)(0), // 0: oipProto.templates.tmpl_6E6D471D.Options
	(*Tmpl_6E6D471D)(nil),      // 1: oipProto.templates.tmpl_6E6D471D
}
var file_tmpl_6E6D471D_proto_depIdxs = []int32{
	0, // 0: oipProto.templates.tmpl_6E6D471D.enum:type_name -> oipProto.templates.tmpl_6E6D471D.Options
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tmpl_6E6D471D_proto_init() }
func file_tmpl_6E6D471D_proto_init() {
	if File_tmpl_6E6D471D_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmpl_6E6D471D_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmpl_6E6D471D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmpl_6E6D471D_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmpl_6E6D471D_proto_goTypes,
		DependencyIndexes: file_tmpl_6E6D471D_proto_depIdxs,
		EnumInfos:         file_tmpl_6E6D471D_proto_enumTypes,
		MessageInfos:      file_tmpl_6E6D471D_proto_msgTypes,
	}.Build()
	File_tmpl_6E6D471D_proto = out.File
	file_tmpl_6E6D471D_proto_rawDesc = nil
	file_tmpl_6E6D471D_proto_goTypes = nil
	file_tmpl_6E6D471D_proto_depIdxs = nil
}
