// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: multipart.proto

package pb_oip

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MultiPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPart uint32 `protobuf:"varint,1,opt,name=currentPart,proto3" json:"currentPart,omitempty"`
	CountParts  uint32 `protobuf:"varint,2,opt,name=countParts,proto3" json:"countParts,omitempty"`
	RawData     []byte `protobuf:"bytes,3,opt,name=rawData,proto3" json:"rawData,omitempty"`
	Reference   *Txid  `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *MultiPart) Reset() {
	*x = MultiPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPart) ProtoMessage() {}

func (x *MultiPart) ProtoReflect() protoreflect.Message {
	mi := &file_multipart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPart.ProtoReflect.Descriptor instead.
func (*MultiPart) Descriptor() ([]byte, []int) {
	return file_multipart_proto_rawDescGZIP(), []int{0}
}

func (x *MultiPart) GetCurrentPart() uint32 {
	if x != nil {
		return x.CurrentPart
	}
	return 0
}

func (x *MultiPart) GetCountParts() uint32 {
	if x != nil {
		return x.CountParts
	}
	return 0
}

func (x *MultiPart) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *MultiPart) GetReference() *Txid {
	if x != nil {
		return x.Reference
	}
	return nil
}

var File_multipart_proto protoreflect.FileDescriptor

var file_multipart_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x74, 0x78, 0x69,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x50, 0x61, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x78, 0x69, 0x64, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69,
	0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f,
	0x6f, 0x69, 0x70, 0x3b, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_multipart_proto_rawDescOnce sync.Once
	file_multipart_proto_rawDescData = file_multipart_proto_rawDesc
)

func file_multipart_proto_rawDescGZIP() []byte {
	file_multipart_proto_rawDescOnce.Do(func() {
		file_multipart_proto_rawDescData = protoimpl.X.CompressGZIP(file_multipart_proto_rawDescData)
	})
	return file_multipart_proto_rawDescData
}

var file_multipart_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multipart_proto_goTypes = []interface{}{
	(*MultiPart)(nil), // 0: oipProto.MultiPart
	(*Txid)(nil),      // 1: oipProto.Txid
}
var file_multipart_proto_depIdxs = []int32{
	1, // 0: oipProto.MultiPart.reference:type_name -> oipProto.Txid
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_multipart_proto_init() }
func file_multipart_proto_init() {
	if File_multipart_proto != nil {
		return
	}
	file_txid_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_multipart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multipart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multipart_proto_goTypes,
		DependencyIndexes: file_multipart_proto_depIdxs,
		MessageInfos:      file_multipart_proto_msgTypes,
	}.Build()
	File_multipart_proto = out.File
	file_multipart_proto_rawDesc = nil
	file_multipart_proto_goTypes = nil
	file_multipart_proto_depIdxs = nil
}
