// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pubkey.proto

package pb_oip

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Currently supported message types
type NetworkTypes int32

const (
	// Invalid
	NetworkTypes_InvalidNetwork NetworkTypes = 0
	// FLO address message signing
	NetworkTypes_FloNetwork NetworkTypes = 1
)

// Enum value maps for NetworkTypes.
var (
	NetworkTypes_name = map[int32]string{
		0: "InvalidNetwork",
		1: "FloNetwork",
	}
	NetworkTypes_value = map[string]int32{
		"InvalidNetwork": 0,
		"FloNetwork":     1,
	}
)

func (x NetworkTypes) Enum() *NetworkTypes {
	p := new(NetworkTypes)
	*p = x
	return p
}

func (x NetworkTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_pubkey_proto_enumTypes[0].Descriptor()
}

func (NetworkTypes) Type() protoreflect.EnumType {
	return &file_pubkey_proto_enumTypes[0]
}

func (x NetworkTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkTypes.Descriptor instead.
func (NetworkTypes) EnumDescriptor() ([]byte, []int) {
	return file_pubkey_proto_rawDescGZIP(), []int{0}
}

type PubKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network NetworkTypes `protobuf:"varint,1,opt,name=network,proto3,enum=oipProto.NetworkTypes" json:"network,omitempty"`
	Raw     []byte       `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *PubKey) Reset() {
	*x = PubKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubkey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKey) ProtoMessage() {}

func (x *PubKey) ProtoReflect() protoreflect.Message {
	mi := &file_pubkey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKey.ProtoReflect.Descriptor instead.
func (*PubKey) Descriptor() ([]byte, []int) {
	return file_pubkey_proto_rawDescGZIP(), []int{0}
}

func (x *PubKey) GetNetwork() NetworkTypes {
	if x != nil {
		return x.Network
	}
	return NetworkTypes_InvalidNetwork
}

func (x *PubKey) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_pubkey_proto protoreflect.FileDescriptor

var file_pubkey_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x2a, 0x32, 0x0a, 0x0c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x6c,
	0x6f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x10, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x3b, 0x70,
	0x62, 0x5f, 0x6f, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pubkey_proto_rawDescOnce sync.Once
	file_pubkey_proto_rawDescData = file_pubkey_proto_rawDesc
)

func file_pubkey_proto_rawDescGZIP() []byte {
	file_pubkey_proto_rawDescOnce.Do(func() {
		file_pubkey_proto_rawDescData = protoimpl.X.CompressGZIP(file_pubkey_proto_rawDescData)
	})
	return file_pubkey_proto_rawDescData
}

var file_pubkey_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pubkey_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pubkey_proto_goTypes = []interface{}{
	(NetworkTypes)(0), // 0: oipProto.NetworkTypes
	(*PubKey)(nil),    // 1: oipProto.PubKey
}
var file_pubkey_proto_depIdxs = []int32{
	0, // 0: oipProto.PubKey.network:type_name -> oipProto.NetworkTypes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pubkey_proto_init() }
func file_pubkey_proto_init() {
	if File_pubkey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pubkey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pubkey_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubkey_proto_goTypes,
		DependencyIndexes: file_pubkey_proto_depIdxs,
		EnumInfos:         file_pubkey_proto_enumTypes,
		MessageInfos:      file_pubkey_proto_msgTypes,
	}.Build()
	File_pubkey_proto = out.File
	file_pubkey_proto_rawDesc = nil
	file_pubkey_proto_goTypes = nil
	file_pubkey_proto_depIdxs = nil
}
