// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: edit.proto

package pb_oip5

import (
	protoPatch "github.com/bitspill/protoPatch"
	proto "github.com/golang/protobuf/proto"
	pb_oip "github.com/oipwg/proto/go/pb_oip"
	pb_templates "github.com/oipwg/proto/go/pb_oip5/pb_templates"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EditProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference *pb_oip.Txid `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	// Types that are assignable to Mod:
	//	*EditProto_Patch
	//	*EditProto_Template
	Mod isEditProto_Mod `protobuf_oneof:"mod"`
}

func (x *EditProto) Reset() {
	*x = EditProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProto) ProtoMessage() {}

func (x *EditProto) ProtoReflect() protoreflect.Message {
	mi := &file_edit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProto.ProtoReflect.Descriptor instead.
func (*EditProto) Descriptor() ([]byte, []int) {
	return file_edit_proto_rawDescGZIP(), []int{0}
}

func (x *EditProto) GetReference() *pb_oip.Txid {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (m *EditProto) GetMod() isEditProto_Mod {
	if m != nil {
		return m.Mod
	}
	return nil
}

func (x *EditProto) GetPatch() *protoPatch.ProtoPatch {
	if x, ok := x.GetMod().(*EditProto_Patch); ok {
		return x.Patch
	}
	return nil
}

func (x *EditProto) GetTemplate() *pb_templates.RecordTemplateProto {
	if x, ok := x.GetMod().(*EditProto_Template); ok {
		return x.Template
	}
	return nil
}

type isEditProto_Mod interface {
	isEditProto_Mod()
}

type EditProto_Patch struct {
	Patch *protoPatch.ProtoPatch `protobuf:"bytes,2,opt,name=patch,proto3,oneof"`
}

type EditProto_Template struct {
	Template *pb_templates.RecordTemplateProto `protobuf:"bytes,3,opt,name=template,proto3,oneof"`
}

func (*EditProto_Patch) isEditProto_Mod() {}

func (*EditProto_Template) isEditProto_Mod() {}

var File_edit_proto protoreflect.FileDescriptor

var file_edit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x69,
	0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x1a, 0x23, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0a, 0x74, 0x78, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x09, 0x45, 0x64,
	0x69, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x69, 0x70,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x78, 0x69, 0x64, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x61, 0x74, 0x63, 0x68, 0x48, 0x00, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x45, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x6f, 0x64, 0x42, 0x2b,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70,
	0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f,
	0x69, 0x70, 0x35, 0x3b, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_edit_proto_rawDescOnce sync.Once
	file_edit_proto_rawDescData = file_edit_proto_rawDesc
)

func file_edit_proto_rawDescGZIP() []byte {
	file_edit_proto_rawDescOnce.Do(func() {
		file_edit_proto_rawDescData = protoimpl.X.CompressGZIP(file_edit_proto_rawDescData)
	})
	return file_edit_proto_rawDescData
}

var file_edit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_edit_proto_goTypes = []interface{}{
	(*EditProto)(nil),                        // 0: oipProto.oip5.EditProto
	(*pb_oip.Txid)(nil),                      // 1: oipProto.Txid
	(*protoPatch.ProtoPatch)(nil),            // 2: patch.ProtoPatch
	(*pb_templates.RecordTemplateProto)(nil), // 3: oipProto.templates.RecordTemplateProto
}
var file_edit_proto_depIdxs = []int32{
	1, // 0: oipProto.oip5.EditProto.reference:type_name -> oipProto.Txid
	2, // 1: oipProto.oip5.EditProto.patch:type_name -> patch.ProtoPatch
	3, // 2: oipProto.oip5.EditProto.template:type_name -> oipProto.templates.RecordTemplateProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_edit_proto_init() }
func file_edit_proto_init() {
	if File_edit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_edit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_edit_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EditProto_Patch)(nil),
		(*EditProto_Template)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edit_proto_goTypes,
		DependencyIndexes: file_edit_proto_depIdxs,
		MessageInfos:      file_edit_proto_msgTypes,
	}.Build()
	File_edit_proto = out.File
	file_edit_proto_rawDesc = nil
	file_edit_proto_goTypes = nil
	file_edit_proto_depIdxs = nil
}
