// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: NormalizeRecord.proto

package pb_oip5

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// https://github.com/golang/protobuf/blob/882cf97/protoc-gen-go/descriptor/descriptor.proto#L136-L168
type Field_Type int32

const (
	// 0 is reserved for errors.
	Field_TYPE_ERROR Field_Type = 0
	// Order is weird for historical reasons.
	Field_TYPE_DOUBLE Field_Type = 1
	Field_TYPE_FLOAT  Field_Type = 2
	// Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT64 if
	// negative values are likely.
	Field_TYPE_INT64  Field_Type = 3
	Field_TYPE_UINT64 Field_Type = 4
	// Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT32 if
	// negative values are likely.
	Field_TYPE_INT32   Field_Type = 5
	Field_TYPE_FIXED64 Field_Type = 6
	Field_TYPE_FIXED32 Field_Type = 7
	Field_TYPE_BOOL    Field_Type = 8
	Field_TYPE_STRING  Field_Type = 9
	// Tag-delimited aggregate.
	// Group type is deprecated and not supported in proto3. However, Proto3
	// implementations should still be able to parse the group wire format and
	// treat group fields as unknown fields.
	Field_TYPE_GROUP   Field_Type = 10
	Field_TYPE_MESSAGE Field_Type = 11 // Length-delimited aggregate.
	// New in version 2.
	Field_TYPE_BYTES    Field_Type = 12
	Field_TYPE_UINT32   Field_Type = 13
	Field_TYPE_ENUM     Field_Type = 14
	Field_TYPE_SFIXED32 Field_Type = 15
	Field_TYPE_SFIXED64 Field_Type = 16
	Field_TYPE_SINT32   Field_Type = 17 // Uses ZigZag encoding.
	Field_TYPE_SINT64   Field_Type = 18 // Uses ZigZag encoding.
)

// Enum value maps for Field_Type.
var (
	Field_Type_name = map[int32]string{
		0:  "TYPE_ERROR",
		1:  "TYPE_DOUBLE",
		2:  "TYPE_FLOAT",
		3:  "TYPE_INT64",
		4:  "TYPE_UINT64",
		5:  "TYPE_INT32",
		6:  "TYPE_FIXED64",
		7:  "TYPE_FIXED32",
		8:  "TYPE_BOOL",
		9:  "TYPE_STRING",
		10: "TYPE_GROUP",
		11: "TYPE_MESSAGE",
		12: "TYPE_BYTES",
		13: "TYPE_UINT32",
		14: "TYPE_ENUM",
		15: "TYPE_SFIXED32",
		16: "TYPE_SFIXED64",
		17: "TYPE_SINT32",
		18: "TYPE_SINT64",
	}
	Field_Type_value = map[string]int32{
		"TYPE_ERROR":    0,
		"TYPE_DOUBLE":   1,
		"TYPE_FLOAT":    2,
		"TYPE_INT64":    3,
		"TYPE_UINT64":   4,
		"TYPE_INT32":    5,
		"TYPE_FIXED64":  6,
		"TYPE_FIXED32":  7,
		"TYPE_BOOL":     8,
		"TYPE_STRING":   9,
		"TYPE_GROUP":    10,
		"TYPE_MESSAGE":  11,
		"TYPE_BYTES":    12,
		"TYPE_UINT32":   13,
		"TYPE_ENUM":     14,
		"TYPE_SFIXED32": 15,
		"TYPE_SFIXED64": 16,
		"TYPE_SINT32":   17,
		"TYPE_SINT64":   18,
	}
)

func (x Field_Type) Enum() *Field_Type {
	p := new(Field_Type)
	*p = x
	return p
}

func (x Field_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_NormalizeRecord_proto_enumTypes[0].Descriptor()
}

func (Field_Type) Type() protoreflect.EnumType {
	return &file_NormalizeRecord_proto_enumTypes[0]
}

func (x Field_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field_Type.Descriptor instead.
func (Field_Type) EnumDescriptor() ([]byte, []int) {
	return file_NormalizeRecord_proto_rawDescGZIP(), []int{2, 0}
}

type NormalizeRecordProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// standard template ID which triggers this meta-type
	MainTemplate uint32 `protobuf:"fixed32,3,opt,name=mainTemplate,proto3" json:"mainTemplate,omitempty"`
	// fields comprising this new meta-type
	Fields []*NormalField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *NormalizeRecordProto) Reset() {
	*x = NormalizeRecordProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NormalizeRecord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalizeRecordProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeRecordProto) ProtoMessage() {}

func (x *NormalizeRecordProto) ProtoReflect() protoreflect.Message {
	mi := &file_NormalizeRecord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeRecordProto.ProtoReflect.Descriptor instead.
func (*NormalizeRecordProto) Descriptor() ([]byte, []int) {
	return file_NormalizeRecord_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizeRecordProto) GetMainTemplate() uint32 {
	if x != nil {
		return x.MainTemplate
	}
	return 0
}

func (x *NormalizeRecordProto) GetFields() []*NormalField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type NormalField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// new ES compatible name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// path to the source value
	Path []*Field `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *NormalField) Reset() {
	*x = NormalField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NormalizeRecord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalField) ProtoMessage() {}

func (x *NormalField) ProtoReflect() protoreflect.Message {
	mi := &file_NormalizeRecord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalField.ProtoReflect.Descriptor instead.
func (*NormalField) Descriptor() ([]byte, []int) {
	return file_NormalizeRecord_proto_rawDescGZIP(), []int{1}
}

func (x *NormalField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NormalField) GetPath() []*Field {
	if x != nil {
		return x.Path
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Tag number in prior Proto message
	Tag int32 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Expected type
	// if type_message resolution proceeds into the message
	// if type_message and type_name == oip.txid resolves linked record before proceeding
	// if type doesn't match field is ignored
	Type Field_Type `protobuf:"varint,2,opt,name=type,proto3,enum=oipProto.oip5.Field_Type" json:"type,omitempty"`
	// Enter specified details template
	// Set either tag/type OR template
	Template uint32 `protobuf:"fixed32,3,opt,name=template,proto3" json:"template,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NormalizeRecord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_NormalizeRecord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_NormalizeRecord_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Field) GetType() Field_Type {
	if x != nil {
		return x.Type
	}
	return Field_TYPE_ERROR
}

func (x *Field) GetTemplate() uint32 {
	if x != nil {
		return x.Template
	}
	return 0
}

var File_NormalizeRecord_proto protoreflect.FileDescriptor

var file_NormalizeRecord_proto_rawDesc = []byte{
	0x0a, 0x15, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x22, 0x6e, 0x0a, 0x14, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22,
	0x0a, 0x0c, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x0c, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69,
	0x70, 0x35, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x4b, 0x0a, 0x0b, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0xad, 0x03, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0xc6, 0x02, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x4f, 0x55, 0x42,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x4c, 0x4f,
	0x41, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x54,
	0x36, 0x34, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x49, 0x4e,
	0x54, 0x36, 0x34, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e,
	0x54, 0x33, 0x32, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49,
	0x58, 0x45, 0x44, 0x36, 0x34, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x46, 0x49, 0x58, 0x45, 0x44, 0x33, 0x32, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x09, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x0c, 0x12, 0x0f, 0x0a, 0x0b, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x0d, 0x12, 0x0d, 0x0a, 0x09,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x10, 0x0e, 0x12, 0x11, 0x0a, 0x0d, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x46, 0x49, 0x58, 0x45, 0x44, 0x33, 0x32, 0x10, 0x0f, 0x12, 0x11,
	0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x46, 0x49, 0x58, 0x45, 0x44, 0x36, 0x34, 0x10,
	0x10, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x49, 0x4e, 0x54, 0x33, 0x32,
	0x10, 0x11, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x49, 0x4e, 0x54, 0x36,
	0x34, 0x10, 0x12, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x3b, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_NormalizeRecord_proto_rawDescOnce sync.Once
	file_NormalizeRecord_proto_rawDescData = file_NormalizeRecord_proto_rawDesc
)

func file_NormalizeRecord_proto_rawDescGZIP() []byte {
	file_NormalizeRecord_proto_rawDescOnce.Do(func() {
		file_NormalizeRecord_proto_rawDescData = protoimpl.X.CompressGZIP(file_NormalizeRecord_proto_rawDescData)
	})
	return file_NormalizeRecord_proto_rawDescData
}

var file_NormalizeRecord_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_NormalizeRecord_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_NormalizeRecord_proto_goTypes = []interface{}{
	(Field_Type)(0),              // 0: oipProto.oip5.Field.Type
	(*NormalizeRecordProto)(nil), // 1: oipProto.oip5.NormalizeRecordProto
	(*NormalField)(nil),          // 2: oipProto.oip5.NormalField
	(*Field)(nil),                // 3: oipProto.oip5.Field
}
var file_NormalizeRecord_proto_depIdxs = []int32{
	2, // 0: oipProto.oip5.NormalizeRecordProto.fields:type_name -> oipProto.oip5.NormalField
	3, // 1: oipProto.oip5.NormalField.path:type_name -> oipProto.oip5.Field
	0, // 2: oipProto.oip5.Field.type:type_name -> oipProto.oip5.Field.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_NormalizeRecord_proto_init() }
func file_NormalizeRecord_proto_init() {
	if File_NormalizeRecord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_NormalizeRecord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalizeRecordProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NormalizeRecord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NormalizeRecord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NormalizeRecord_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NormalizeRecord_proto_goTypes,
		DependencyIndexes: file_NormalizeRecord_proto_depIdxs,
		EnumInfos:         file_NormalizeRecord_proto_enumTypes,
		MessageInfos:      file_NormalizeRecord_proto_msgTypes,
	}.Build()
	File_NormalizeRecord_proto = out.File
	file_NormalizeRecord_proto_rawDesc = nil
	file_NormalizeRecord_proto_goTypes = nil
	file_NormalizeRecord_proto_depIdxs = nil
}
