// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: oip5.proto

package pb_oip5

import (
	proto "github.com/golang/protobuf/proto"
	pb_oip "github.com/oipwg/proto/go/pb_oip"
	pb_templates "github.com/oipwg/proto/go/pb_oip5/pb_templates"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OipFive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordTemplate *pb_templates.RecordTemplateProto `protobuf:"bytes,1,opt,name=recordTemplate,proto3" json:"recordTemplate,omitempty"`
	Record         *RecordProto                      `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Normalize      *NormalizeRecordProto             `protobuf:"bytes,3,opt,name=normalize,proto3" json:"normalize,omitempty"`
	Transfer       *Transfer                         `protobuf:"bytes,7,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Deactivate     *Deactivate                       `protobuf:"bytes,8,opt,name=deactivate,proto3" json:"deactivate,omitempty"`
	Edit           *EditProto                        `protobuf:"bytes,9,opt,name=edit,proto3" json:"edit,omitempty"`
}

func (x *OipFive) Reset() {
	*x = OipFive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oip5_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OipFive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OipFive) ProtoMessage() {}

func (x *OipFive) ProtoReflect() protoreflect.Message {
	mi := &file_oip5_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OipFive.ProtoReflect.Descriptor instead.
func (*OipFive) Descriptor() ([]byte, []int) {
	return file_oip5_proto_rawDescGZIP(), []int{0}
}

func (x *OipFive) GetRecordTemplate() *pb_templates.RecordTemplateProto {
	if x != nil {
		return x.RecordTemplate
	}
	return nil
}

func (x *OipFive) GetRecord() *RecordProto {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *OipFive) GetNormalize() *NormalizeRecordProto {
	if x != nil {
		return x.Normalize
	}
	return nil
}

func (x *OipFive) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *OipFive) GetDeactivate() *Deactivate {
	if x != nil {
		return x.Deactivate
	}
	return nil
}

func (x *OipFive) GetEdit() *EditProto {
	if x != nil {
		return x.Edit
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oip5_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_oip5_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_oip5_proto_rawDescGZIP(), []int{1}
}

type Deactivate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid *pb_oip.Txid `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (x *Deactivate) Reset() {
	*x = Deactivate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oip5_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deactivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deactivate) ProtoMessage() {}

func (x *Deactivate) ProtoReflect() protoreflect.Message {
	mi := &file_oip5_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deactivate.ProtoReflect.Descriptor instead.
func (*Deactivate) Descriptor() ([]byte, []int) {
	return file_oip5_proto_rawDescGZIP(), []int{2}
}

func (x *Deactivate) GetTxid() *pb_oip.Txid {
	if x != nil {
		return x.Txid
	}
	return nil
}

var File_oip5_proto protoreflect.FileDescriptor

var file_oip5_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x69, 0x70, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x69,
	0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x1a, 0x0c, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x2f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x74, 0x78, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xef, 0x02,
	0x0a, 0x07, 0x4f, 0x69, 0x70, 0x46, 0x69, 0x76, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x69, 0x70,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x41,
	0x0a, 0x09, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70,
	0x35, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x12, 0x33, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f,
	0x69, 0x70, 0x35, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x08, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x69, 0x70,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x2e, 0x44, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x12, 0x2c, 0x0a, 0x04, 0x65, 0x64, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x70, 0x35, 0x2e,
	0x45, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x65, 0x64, 0x69, 0x74, 0x22,
	0x0a, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x0a, 0x44,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x78, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x69, 0x70, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x78, 0x69, 0x64, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x69, 0x70, 0x77,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6f, 0x69,
	0x70, 0x35, 0x3b, 0x70, 0x62, 0x5f, 0x6f, 0x69, 0x70, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_oip5_proto_rawDescOnce sync.Once
	file_oip5_proto_rawDescData = file_oip5_proto_rawDesc
)

func file_oip5_proto_rawDescGZIP() []byte {
	file_oip5_proto_rawDescOnce.Do(func() {
		file_oip5_proto_rawDescData = protoimpl.X.CompressGZIP(file_oip5_proto_rawDescData)
	})
	return file_oip5_proto_rawDescData
}

var file_oip5_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oip5_proto_goTypes = []interface{}{
	(*OipFive)(nil),                          // 0: oipProto.oip5.OipFive
	(*Transfer)(nil),                         // 1: oipProto.oip5.Transfer
	(*Deactivate)(nil),                       // 2: oipProto.oip5.Deactivate
	(*pb_templates.RecordTemplateProto)(nil), // 3: oipProto.templates.RecordTemplateProto
	(*RecordProto)(nil),                      // 4: oipProto.oip5.RecordProto
	(*NormalizeRecordProto)(nil),             // 5: oipProto.oip5.NormalizeRecordProto
	(*EditProto)(nil),                        // 6: oipProto.oip5.EditProto
	(*pb_oip.Txid)(nil),                      // 7: oipProto.Txid
}
var file_oip5_proto_depIdxs = []int32{
	3, // 0: oipProto.oip5.OipFive.recordTemplate:type_name -> oipProto.templates.RecordTemplateProto
	4, // 1: oipProto.oip5.OipFive.record:type_name -> oipProto.oip5.RecordProto
	5, // 2: oipProto.oip5.OipFive.normalize:type_name -> oipProto.oip5.NormalizeRecordProto
	1, // 3: oipProto.oip5.OipFive.transfer:type_name -> oipProto.oip5.Transfer
	2, // 4: oipProto.oip5.OipFive.deactivate:type_name -> oipProto.oip5.Deactivate
	6, // 5: oipProto.oip5.OipFive.edit:type_name -> oipProto.oip5.EditProto
	7, // 6: oipProto.oip5.Deactivate.txid:type_name -> oipProto.Txid
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_oip5_proto_init() }
func file_oip5_proto_init() {
	if File_oip5_proto != nil {
		return
	}
	file_Record_proto_init()
	file_NormalizeRecord_proto_init()
	file_edit_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_oip5_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OipFive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oip5_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oip5_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deactivate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oip5_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oip5_proto_goTypes,
		DependencyIndexes: file_oip5_proto_depIdxs,
		MessageInfos:      file_oip5_proto_msgTypes,
	}.Build()
	File_oip5_proto = out.File
	file_oip5_proto_rawDesc = nil
	file_oip5_proto_goTypes = nil
	file_oip5_proto_depIdxs = nil
}
